language: python

env:
  global:
    - SSH_KEY="travis_key"
    - GIT_NAME="Jarret Lavallee"
    - GIT_EMAIL="jarret.lavallee@gmail.com"
    - SOURCE_DIR="output"
    - DEPLOY_BRANCH="code"
    - TEMP_DIR=$(sudo mktemp -d /tmp/$REPO_NAME.XXXX)

before_install:
        - openssl aes-256-cbc -K $encrypted_ee44e910a59a_key -iv $encrypted_ee44e910a59a_iv -in travis_key.enc -out travis_key -d

install:
  # https://github.com/wummel/linkchecker/issues/649
  - pip install requests==2.9.1
  - pip install LinkChecker==9.3
  - pip install pelican markdown

  # grab the build theme
  - git clone https://github.com/getpelican/pelican-themes.git

  # grab the pelican plugins
  - git clone https://github.com/getpelican/pelican-plugins

script:
  - linkchecker --check-extern ./content
  - pelican

after_success:
  - chmod a+x ./scripts/deploy.sh
  - ./scripts/deploy.sh
