---
baseURL: "https://beer.hubnut.ga/"
languageCode: "en-us"
title: "1709 Brewing"
Subtitle: "A weird brewing blog"

# Theme settings
theme: hello-programmer
paginate: 2
name: "1709 Brewing"
licenselink: https://opensource.org/licenses/MIT
description: "A weird brewing blog"
homepage: "https://beer.hubnut.ga"

author:
  name: "jarret"
  email: "jarret.lavallee@gmail.com"
